### ISSUE TITLE
Error when running "make k8s-infra-deploy"

### ISSUE THREAD

**Issue by quangtamle** [ligato/networkservicemesh#620]
Hello everyone,

When I tried to running  "make k8s-infra-deploy", I faced this issue:

" The DaemonSet "nsm-vppagent-dataplane" is invalid: 
spec.template.spec.containers[0].securityContext.privileged: Forbidden: disallowed by cluster policy
make: *** [.k8s.mk:68: k8s-vppagent-dataplane-deploy] Error 1
"
![error](https://user-images.githubusercontent.com/43220759/50281391-9af22a00-044f-11e9-8abc-5039cdb94cd6.png)

Have anyone face this issue like mine ??? and how could I fix it ???

Thank you in advance !!!

**Comment by edwarnicke** [comment]
@quangtamle It looks like your cluster policy is setup to forbid privileged containers or containers with host:pid.  We take great care to limit the scope of such privilege in NSM, so only the dataplane requires it... but it *does* require it to insert kernel interfaces into namespaces etc.

It looks like you need to setup [RBAC](https://kubernetes.io/docs/concepts/policy/pod-security-policy/) to allow privileged and host:pid for whatever user is deploying your vppagent-dataplane Daemonset.

**Comment by nickolaev** [comment]
@quangtamle I wonder why you are using `sudo`? It would not be needed in the general case.
I see your logs show that you use vagrant? Can you tell us if you changed something in the deployment files or process? I would expect that if `make vagrant-start` finishes successfully, everything in the VMs should be set as we expect it to be.

**Comment by quangtamle** [comment]
Hi @edwarnicke @nickolaev 
Without using sudo, I can not run those command such as "make k8s-deploy", "make k8s-infra"... or even "vagrant halt", I attach the photos, you can check it.
Yes, i am using vagrant and for sure I did not change anything in the config files
![with and without sudo](https://user-images.githubusercontent.com/43220759/50397032-e0736780-076d-11e9-9302-e83853bfa5cb.png)
![without sudo](https://user-images.githubusercontent.com/43220759/50397034-e406ee80-076d-11e9-8ff7-429c3f64b5b1.png)
![with sudo](https://user-images.githubusercontent.com/43220759/50397039-e6694880-076d-11e9-9857-6fb676b55b05.png)

**Comment by edwarnicke** [comment]
@quangtamle It looks like you created your vagrant with root, and no can't manage it with a non-root account.  My suggestion would be

```bash
sudo vagrant destroy
sudo rm -rf .vagrant
```

and then try again without sudo.

**Comment by quangtamle** [comment]
hi @edwarnicke ,
I try 
sudo vagrant destroy
sudo rm -rf .vagrant
It only worked for a while, after I started the vagrant again, it back to root again. Moreover, it also happend with "make" command. Do i need to switch it to non-root account because using "sudo" is ok with me ???
By the way, you suggest me using RBAC to allow privileged and host:pid for whatever user is deploying vppagent-dataplane Daemonset. Could you show me how to do this in this situation ???

Thank you

**Comment by quangtamle** [comment]
Hi @edwarnicke 
I try
sudo vagrant destroy
sudo rm -rf .vagrant
It only worked for a while, after I started the vagrant again, it back to root again. Moreover, it also happend with "make" command. Do i need to switch it to non-root account because using "sudo" is ok with me ???
By the way, you suggest me using RBAC to allow privileged and host:pid for whatever user is deploying vppagent-dataplane Daemonset. I tried to change from "True" to "False"
![true](https://user-images.githubusercontent.com/43220759/50495734-59531780-0a2b-11e9-9b17-51f0d4290af0.png)
in this file
![vpp](https://user-images.githubusercontent.com/43220759/50495736-5c4e0800-0a2b-11e9-8667-b04eeb0bbca2.png)
then i re-run "make k8s-infra-deploy" then I get this:
![another](https://user-images.githubusercontent.com/43220759/50495767-95867800-0a2b-11e9-9d6f-e348faf8097a.png)
Did I do right ?? Could you help me correct it if i did wrong ???
Thank you

**Comment by nickolaev** [comment]
Hi @quangtamle, we have merged an updated quick start instructions here: https://github.com/ligato/networkservicemesh/blob/master/docs/QUICK-START.md They assume you start froma a clean environment (i.e. freshly installed OS). Obviously, something got wrong in your installation, you should be able to fix it by following the Vagrant docs like this https://www.vagrantup.com/docs/cli/destroy.html The other options is to start from a clean OS installation. You should not need editing YAMLs or using sudo.

**Comment by quangtamle** [comment]
Hi @nickolaev @edwarnicke 

I tried to reinstall ubuntu 18.04 (freshly installed OS) and follow all your instruction step by step from QUICK START but the problem still happends, exactly the same as previous one.

What should I do now ??? I am so confused, I have 2 laptops and I did exactly the same actions on both of this laptop independently but the results I got are the same.

**Comment by quangtamle** [comment]
Hi @nickolaev 

After compare your install.log with mine, i see no difference. The difference happends in "make k8s-infra-deploy"
[make k8s-deploy log](https://github.com/ligato/networkservicemesh/files/2715144/make.k8s-deploy.log)
[make k8s-infra-deploy.log](https://github.com/ligato/networkservicemesh/files/2715147/make.k8s-infra-deploy.log)

Here is vagrant version and VBoxManage --version:
![version](https://user-images.githubusercontent.com/43220759/50520322-f790bd00-0abf-11e9-90e1-2b553c97e016.png)

**Comment by nickolaev** [comment]
@quangtamle hmm, are you sure you have done `source scripts/vagrant/env.sh` before running `make k8s-infra-deploy`?
Can you check if you see the following:
```bash
$ kubectl get nodes
NAME          STATUS   ROLES    AGE     VERSION
kube-master   Ready    master   3d17h   v1.13.1
kube-worker   Ready    <none>   3d17h   v1.13.1
```

**Comment by quangtamle** [comment]
Hi @nickolaev 
I am sure about that but there is a problem if I ssh to the master node and show "kubectl get nodes", I got the same result like yours but if I am in my home directory, i got the difference result.
![abc](https://user-images.githubusercontent.com/43220759/50524162-81e31c00-0ad4-11e9-9f3e-f847017e19af.png)
